"""remove document_id from chat_sessions

Revision ID: 9772f58b4cd4
Revises: c5619ddf014c
Create Date: 2026-04-23 15:37:24.600448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9772f58b4cd4'
down_revision: Union[str, Sequence[str], None] = 'c5619ddf014c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_constraint(op.f('chat_sessions_document_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
 
    op.add_column('chat_sessions', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('chat_sessions_document_id_fkey'), 'chat_sessions', 'documents', ['document_id'], ['id'])
    
    # ### end Alembic commands ###
